version: "3"
services:
  db:
    build:
      context: ./db
      args:
        - USERS_PASSWORD=${DB_USERS_PASSWORD:?db users password must be set}
    volumes:
        - ${DB_FILES_PATH:?db files path must be specified so that you never loose them}:/var/lib/postgresql/data

  db_for_tests:
    build:
      context: ./db-for-tests
      args:
        - LIVE_DB_PATH=/live_db_files/
    volumes:
        - ${DB_FILES_PATH:?db files path must be specified so that you never loose them}:/live_db_files/

  server_app:
    build:
      context: ./server-app
      args:
        - VK_SERVER_TOKEN=${VK_SERVER_TOKEN:?vk server token must be set}
        - LIVE_DB_HOSTNAME=db
        - TEST_DB_HOSTNAME=db_for_tests
        - DB_USERS_PASSWORD=${DB_USERS_PASSWORD:?db users password must be set}
        - SERVER_ADDRESS=127.0.0.1:8765
    depends_on:
      - db
      - db_for_tests
    restart: always
