version: "3"
services:
  db:
    build:
      context: ./db
      args:
        - USERS_PASSWORD=${DB_USERS_PASSWORD:?db users password must be set}
    volumes:
        - ${DB_FILES_PATH:?db files path must be specified so that you never loose them}:/var/lib/postgresql/data

  db_for_tests:
    build:
      context: ./db-for-tests
      args:
        - LIVE_DB_PATH=/live_db_files
    volumes:
        - ${DB_FILES_PATH:?db files path must be specified so that you never loose them}:/live_db_files
    depends_on:
      - db
    restart: always

  server_app:
    build:
      context: ./server-app
      args:
        - VK_SERVER_TOKEN=${VK_SERVER_TOKEN:?vk server token must be set}
        - LIVE_DB_HOSTNAME=db
        - TEST_DB_HOSTNAME=db_for_tests
        - DB_USERS_PASSWORD=${DB_USERS_PASSWORD:?db users password must be set}
        - SERVER_ADDRESS=server_app:8765
    depends_on:
      - db
      - db_for_tests
    restart: always

  nginx:
    build:
      context: ./nginx
      args:
        - LOCAL_SERVER_ADDRESS=server_app:8765
        - GLOBAL_SERVER_ADDRESS=${GLOBAL_SERVER_ADDRESS:?global server address must be set}
        - DHPARAM_PATH=/etc/keys/dhparam-2048.pem
        - CERTIFICATE_PATH=/etc/keys/fullchain.pem
        - CERTIFICATE_KEY_PATH=/etc/keys/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PATH_TO_KEYS:?}/dhparam-2048.pem:/etc/keys/dhparam-2048.pem
      - ${PATH_TO_KEYS:?}/fullchain.pem:/etc/keys/fullchain.pem
      - ${PATH_TO_KEYS:?}/privkey.pem:/etc/keys/privkey.pem
    depends_on:
      - server_app

  certificate-renewer:
    build:
      context: ./certificate-renewer
    volumes:
      - ${CERTBOT_CONFIG_DIR:?}:/etc/letsencrypt
      - ${CERTBOT_WORK_DIR:?}:/var/lib/letsencrypt
      - ${CERTBOT_LOG_DIR:?}:/var/logs/letsencrypt
